#!/bin/bash

ENVFILE="/var/lib/environment/compositor/droid-hal-device.conf"
REMOVESTRING=":filtered:prediction=16"
RESTORETOKEN="evdevtouch:/dev/touchscreen"
CONTAINS_REMOVESTRING=`cat $ENVFILE | grep $REMOVESTRING | wc -l`

if [ "$1" == "restore" ]; then
    sed -i "s|${RESTORETOKEN}|${RESTORETOKEN}${REMOVESTRING}|g" $ENVFILE
    echo "Kalman filter restored, proceeding."
    exit 0
fi

if [ "$CONTAINS_REMOVESTRING" != "0" ]; then
    sed -i "s|${REMOVESTRING}||g" $ENVFILE
    echo "Removed Kalman filter, proceeding."
fi

exit 0
